# Generated by Django 4.1.5 on 2023-01-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_statud',
            new_name='payment_status',
        ),
    ]
